Vagrant.configure(2) do |config|	  
  config.vm.box = "ubuntu/trusty64"  	
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "docker-example-vm"
    vb.memory = "1024"
    vb.cpus = 1
  end
    	
  config.vm.provision "docker" do |d|
    d.run "redis",
      args: '--name redis -p 6379:6379'
  end
end