Vagrant.configure(2) do |config|	  
  config.vm.box = "ubuntu/trusty64"  	
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "example-vm"
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  config.vm.provision "shell",
    inline: "sudo apt-get update && sudo apt-get install -y nginx"
end