Vagrant.configure(2) do |config|	  
  config.vm.box = "ubuntu/trusty64"  	
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "docker-example-vm"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "docker" do |d|
    d.pull_images "redis"
  end

  config.vm.provision "shell" do |sh|
    sh.path = 'provisioning/install-docker-compose.sh'
  end

  config.vm.provision "shell" do |sh|
    sh.inline = 'docker-compose -f /vagrant/docker/docker-compose.yml up -d --build'
  end
end